###########################################################################
#
# Generated by : Version 10.1 Build 153 11/29/2010 SJ Web Edition
#
# Project      : aoOCS
# Revision     : aoOCS
#
# Date         : Sun Dec 19 19:30:28 CET 2010
#
###########################################################################
 
 
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: clk_50
create_clock -period "20.000 ns" \
             -name {clk_50} {clk_50}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------

